2021-02-17 20:19:03,173	INFO resource_spec.py:212 -- Starting Ray with 2.2 GiB memory available for workers and up to 1.1 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2021-02-17 20:19:03,525	INFO services.py:1170 -- View the Ray dashboard at [1m[32mlocalhost:8265[39m[22m
2021-02-17 20:19:04,104	INFO trainer.py:421 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
2021-02-17 20:19:04,157	INFO trainer.py:580 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
==================================================
{'grid_mode': False,
 'height': 25,
 'max_num_cities': 4,
 'max_rails_between_cities': 2,
 'max_rails_in_city': 3,
 'number_of_agents': 5,
 'regenerate_rail_on_reset': True,
 'regenerate_schedule_on_reset': True,
 'seed': 1234,
 'width': 25}
==================================================
/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/flatland/envs/rail_generators.py:725: UserWarning: Could not set all required cities!
  "Could not set all required cities!")
2021-02-17 20:19:11,807	INFO trainable.py:217 -- Getting current IP.
Traceback (most recent call last):
  File "rollout.py", line 613, in <module>
    run(args, parser)
  File "rollout.py", line 331, in run
    agent.restore(args.checkpoint)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/tune/trainable.py", line 417, in restore
    self._restore(checkpoint_path)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 633, in _restore
    self.__setstate__(extra_data)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 196, in __setstate__
    Trainer.__setstate__(self, state)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1059, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 787, in restore
    self.policy_map[pid].set_state(state)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/rllib/policy/policy.py", line 325, in set_state
    self.set_weights(state)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py", line 357, in set_weights
    return self._variables.set_weights(weights)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/ray/experimental/tf_utils.py", line 194, in set_weights
    for (name, value) in new_weights.items()
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/Users/stlp/opt/anaconda3/envs/flatland-baseline-cpu-env/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1159, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (256, 256) for Tensor 'default_policy/Placeholder_default_policy/fc_out/kernel:0', which has shape '(256, 5)'
